config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#welcome'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :restaurants do
    resources :pins do 
    end
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :restaurant
	
	acts_as_votable
	belongs_to :user
	
	has_attached_file :image, styles: {  } # These did have this in them but it prevented from saving an image so I took out:     medium: "300x300>"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end
 

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :pins
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :restaurants
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	
	# before_action :set_restaurant
	# before_action :set_pin, except: [:create]

	# def create
	# 	@pin = @restaurant.pins.create(pin_params)
	# 	redirect_to @restaurant 
	# end

	# def destroy
	# 	if @pin.destroy
	# 		flash[:success] = "Pin was deleted"
	# 	else
	# 		flash[:error] = "Pin could not be deleted dude."	
	# 	end
	# 	redirect_to @restaurant	
	# end

	# def complete
	# 	@pin.update_attribute(:completed_at, Time.now)
	# 	redirect_to @restaurant, notice: "Todo item completed dude"
	# end


	# private

	# def set_restaurant 
	# 	@restaurant = TodoList.find(params[:restaurant_id])
	# end

	# def set_pin
	# 	@pin = @restaurant.pins.find(params[:id])		
	# end

	# def pin_params
	# 	params[:pin].permit(:content)
	# end




	before_action :authenticate_user!
	before_action :set_restaurant

	def create
		@pin = @restaurant.pins.create(pin_params)
		redirect_to @restaurant 
	end


	private

	def set_restaurant 
		@restaurant = Restaurant.find(params[:restaurant_id])
	end

	def pin_params
		params[:pin].permit(:image, :title, :description)
	end







	# before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	# before_action :authenticate_user!, except: [:index, :show]
	
	# def index
	# 	@pins = Pin.all.order("created_at DESC")
	# end

	# def show
	# end

	# def new
	# 	@pin = current_user.pins.build
	# end

	# def create
	# 	@pin = current_user.pins.build(pin_params)

	# 	if @pin.save 
	# 		redirect_to @pin, notice: "Successfully created new Pin" 
	# 	else 
	# 		render 'new'
	# 	end
	# end

	# def edit
	# end

	# def update
	# 	if @pin.update(pin_params)
	# 		redirect_to @pin, notice: "Pin was Successfully updated"
	# 	else
	# 		render 'edit'
	# 	end
	# end

	# def destroy
	# 	@pin.destroy
	# 	redirect_to root_path
	# end

	# def upvote
	# 	@pin.upvote_by current_user
	# 	redirect_to :back
	# end   


	# private

	# def pin_params
	# 	params.require(:pin).permit(:title, :description, :image)
	# end

	# def find_pin
	# 	@pin = Pin.find(params[:id])
	# end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def new
		@user = User.new
	end

	private
 
	def sign_up_params
	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def account_update_params
	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Your Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Your Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path, notice: 'The Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:title, :description)
    end



  # before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # respond_to :html

  # def welcome
  # end
  
  # def index
  #   @restaurants = Restaurant.all.order("created_at DESC")
  #   # @restaurants = Restaurant.all
  #   respond_with(@restaurants)
  # end

  # def show
  #   respond_with(@restaurant)
  # end

  # def new
  #   @restaurant = current_user.Restaurants.build
  #   respond_with(@restaurant)
  # end

  # def edit
  # end

  # def create
  #   @restaurant = Restaurant.new(restaurant_params)
  #   @restaurant.save
  #   respond_with(@restaurant)
  # end



  # def update
  #   @restaurant.update(restaurant_params)
  #   respond_with(@restaurant)
  # end

  # def destroy
  #   @restaurant.destroy
  #   respond_with(@restaurant)
  # end

  # private

  #   def set_restaurant
  #     @restaurant = Restaurant.find(params[:id])
  #   end

  #   def restaurant_params
  #     params.require(:restaurant).permit(:title, :description, :address, :comments)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Yummy Yucky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Yummy Yucky", root_path %>
      </div>
      <% if user_signed_in? #some conditional links for if hte user is signed in. %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Account", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info"  %> <!-- this is bootstrap -->
    <% end %>
    <%= yield %>
  </div>
  
</body>
</html>

<!-- the above in haml 
!!! 5
%html
%head
	%title Yummy Yucky
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Yummy Yucky", root_path

			- if user_signed_in? #some conditional links for if hte user is signed in.
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Dish", new_pin_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info" # this is bootstrap
		= yield
 -->

app/views/pins/_form.html.erb
<%= simple_form_for ([@restaurant, @restaurant.pins.build]) do |f| %>
  
  <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control'} %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>



<!--  = simple_form_for @pin, html: {multipart: true} do |f|
 	- if @pin.errors.any? 
 		#errors
 		%h2
 		= pluralize(@pin.errors.count, "error")
 		prevented this Pin from saving
 		%ul
 		- @pin.errors.full_messages.each do |msg|
 			%li = msg

 	.form-group         
 		= f.input :image, input_html: { class: 'form-control'}

 	.form-group
 		= f.input :title, input_html: { class: 'form-control'}

 	.form-group
 		= f.input :description, input_html: { class: 'form-control'}

 	= f.button :submit, class: "btn btn-primary" -->

app/views/pins/_pin.html.erb

<p> <%= pin.title %></p>
<p> <%= pin.description %></p>

app/views/pins/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit This Dish</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Current Image</strong>
          <%= image_tag @pin.image.url() %> <!-- was passing in :medium here but it cause a broken image icon in broswer so i took it out.  -->
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>



<!-- / .col-md-6.col-md-offset-3

/ 	%h1 Edit Pin
/ 	= image_tag @pin.image.url#(:medium)
/ 	= render 'form'
/ 	= link_to "Cancel", pin_path

#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit This Dish
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url() #was passing in :medium here but it cause a broken image icon in broswer so i took it out. 
				= render 'form' -->
				

app/views/pins/index.html.erb
<div> 
  <%= link_to "New Dish", new_restaurant_pin_path %>
</div>

<div class="transitions-enabled" id="pins">
  <% @restaurant_id.pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url), pin %>
      <div class="panel-body"></div>
      <h2>
        <%= link_to pin.title, pin %>
      </h2>
      <p class="user">
        <!-- Submitted by
        -->
        <!-- / = pin.user.email
        -->
      </p>
    </div>
  <% end %>
</div>




<!-- #pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url), pin
			.panel-body	 
			%h2= link_to pin.title, pin
			%p.user
				/ Submitted by
				/ / = pin.user.email -->

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Form</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>



<!-- .col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Form
			.panel-body
				= render 'form' -->


app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8" "col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
        <p></p>
   <!--      Submitted by
        <%= @pin.user.email %> -->
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user"></p>
            Submitted by
            <%= @pin.user.email %>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- The above html.erb in haml:
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
				%p
				Submitted by
				= @pin.user.email
			.panel-footer
				.row
					.col-md-6
						%p.user
						Submitted by
						= @pin.user.email
					.col-md-6
						.btn-group.pull-right
							- if user_signed_in?
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
-->

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :comments %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Kenny's Restaurants</h1>
<%= link_to 'Create New Restaurant', new_restaurant_path %>

<!-- <div class="links">
  <%= link_to "New Restaurant div", new_restaurant_path %>
</div> --> 

<% @restaurants.each do |restaurant| %>
  <div class="index_row clearfix">
    <h2 class="restaurant_title"><%=  restaurant.title %></h2>
    <p class="restaurant_sub_title"><%= restaurant.description %></p>

    <div class="todo_list_menu">
      <%= link_to "My Dishes", restaurant %>  &nbsp;   | &nbsp;  
      <%= link_to "New pin/dish", restaurant %>  &nbsp;   | &nbsp;
      <%= link_to "Restaurant Details", restaurant %>   &nbsp;   | &nbsp;
      <%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div >

  </div>
<% end %>

 

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @restaurant.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @restaurant.comments %>
</p>

<br>

<h4> This Restaurant's Dishes</h4>


<div class="transitions-enabled" id="pins">
  <% @restaurant.pins.each do |pin| %>
    <div class="box panel panel-default">
    <%= render @restaurant.pins %>
      <div class="panel-body"></div>

      <p class="user">
        <!-- Submitted by
        -->
        <!-- / = pin.user.email
        -->
      </p>
    </div>
  <% end %>
</div>


<h3>Create a new Dish</h3>

<div id="form">
  <%= render "pins/form" %>
</div>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/welcome.html.erb
<h1>Welcome to Yummy Yucky</h1>

<%= link_to 'See Restaurants', restaurants_path %>  | &nbsp;  
<%= link_to 'Create New Restaurant', new_restaurant_path %>